In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import tensorflow as tf

# Load the preprocessed dataset
# preprocessed_filename = "../data/pre_processed/preprocessed_nf_uq_nids_haaa.csv"
# data = pd.read_csv(preprocessed_filename)


In [3]:

# Encode categorical labels
label_encoder = LabelEncoder()
data['Label'] = label_encoder.fit_transform(data['Label'])

# Separate features and labels
X = data.drop('Label', axis=1).values
y = data['Label'].values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [6]:
X_train


array([[-0.99999948, -0.99999886, -0.99999836, -0.99999852, -1.        ,
         0.99999953],
       [-0.99999028, -0.99999114, -0.99997215, -0.99997776,  0.96412556,
         0.94604243],
       [-0.9999989 , -0.99999929, -0.99999672, -0.99999852, -0.78475336,
         0.99997113],
       ...,
       [-0.99999965, -1.        , -0.99999836, -1.        , -0.8206278 ,
        -1.        ],
       [-0.99999616, -0.99999646, -0.99998362, -0.99998517, -0.73991031,
         0.96962491],
       [-0.99999943, -0.99999914, -0.99999836, -0.99999852, -1.        ,
         0.9999865 ]])

In [7]:
y_train

array([0, 0, 0, ..., 1, 0, 0])

In [8]:

# Train the Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [9]:

# Evaluate the model on the testing data
y_pred = rf_model.predict(X_test)
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99   1840783
           1       0.98      0.94      0.96    558196

    accuracy                           0.98   2398979
   macro avg       0.98      0.97      0.97   2398979
weighted avg       0.98      0.98      0.98   2398979

Confusion Matrix:
[[1832743    8040]
 [  34830  523366]]
Accuracy Score: 0.9821298977606724


In [15]:
rf_model.predict(X_test[0:1])

array([0])

In [20]:
X_test[0:1]

array([[-0.99999893, -0.99999841, -0.99999672, -0.99999703, -1.        ,
        -1.        ]])

In [21]:
# Check the input data
print("Input Data (X_test[0:1]):")
print(X_test[0:1])

# Predict the class for the given row
prediction = rf_model.predict(X_test[0:1])
print("Predicted Class:", prediction)

# Compare with the actual label
actual_label = y_test[0:1]
print("Actual Label:", actual_label)

# Check if the prediction is correct
is_correct = prediction == actual_label
print("Is the prediction correct?", is_correct)

Input Data (X_test[0:1]):
[[-0.99999893 -0.99999841 -0.99999672 -0.99999703 -1.         -1.        ]]
Predicted Class: [0]
Actual Label: [0]
Is the prediction correct? [ True]


comparision

In [22]:

# Load the saved generator model
generator = tf.keras.models.load_model('generator.h5')

# Parameters
num_samples = 1000  # Number of samples to generate
noise_dim = 100  # Dimension of the noise vector

# Generate noise
noise = np.random.normal(0, 1, (num_samples, noise_dim))

# Generate synthetic attack data
synthetic_data = generator.predict(noise)  # Use predict method for generating data

# Inverse transform to original scale
synthetic_data = scaler.inverse_transform(synthetic_data)

# Create labels for synthetic data (assuming 1 represents "attack")
synthetic_labels = np.ones((num_samples,))


32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [23]:

# Evaluate the model on the synthetic attack data
synthetic_pred = rf_model.predict(synthetic_data)
print("Classification Report for Synthetic Data:")
print(classification_report(synthetic_labels, synthetic_pred))
print("Confusion Matrix for Synthetic Data:")
print(confusion_matrix(synthetic_labels, synthetic_pred))
print("Accuracy Score for Synthetic Data:", accuracy_score(synthetic_labels, synthetic_pred))

Classification Report for Synthetic Data:
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00       0.0
         1.0       0.00      0.00      0.00    1000.0

    accuracy                           0.00    1000.0
   macro avg       0.00      0.00      0.00    1000.0
weighted avg       0.00      0.00      0.00    1000.0

Confusion Matrix for Synthetic Data:
[[   0    0]
 [1000    0]]
Accuracy Score for Synthetic Data: 0.0


/Users/sanjanathyady/Desktop/project-2/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/sanjanathyady/Desktop/project-2/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/sanjanathyady/Desktop/project-2/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, 

In [26]:

# Load the new dataset
new_data_filename = "/Users/sanjanathyady/Desktop/project-2/backend/ids/advanced_synthetic_data.csv"
new_data = pd.read_csv(new_data_filename)

# Drop the Label column
X_new = new_data.drop('Label', axis=1).values

# Predict using the Random Forest model
predictions = rf_model.predict(X_new)

# Print the predictions
print("Predictions for the new dataset:")
print(predictions)

Predictions for the new dataset:
[0 0 0 ... 0 0 0]


In [27]:

# Save the predictions in a new CSV file
predictions_df = pd.DataFrame(predictions, columns=['Predicted_Label'])
output_filename = "predictions.csv"
predictions_df.to_csv(output_filename, index=False)

print(f"Predictions saved to {output_filename}")

Predictions saved to predictions.csv


In [29]:
import joblib
# Save the Random Forest model
model_filename = 'random_forest_model.joblib'
joblib.dump(rf_model, model_filename)
print(f"Random Forest model saved to {model_filename}")


Random Forest model saved to random_forest_model.joblib


In [12]:
import matplotlib.pyplot as plt
import seaborn as sns


# Parameters
num_samples = 1000  # Number of samples to generate
noise_dim = 100  # Dimension of the noise vector

# Generate noise
noise = np.random.normal(0, 1, (num_samples, noise_dim))

# Generate synthetic attack data
synthetic_data = generator.predict(noise)  # Use predict method for generating data

# Inverse transform to original scale
scaler = MinMaxScaler(feature_range=(-1, 1))
scaler.fit(X)  # Fit scaler on the entire dataset
synthetic_data = scaler.inverse_transform(synthetic_data)

# Create labels for synthetic data (assuming 1 represents "attack")
synthetic_labels = np.ones((num_samples,))

# Evaluate the model on the synthetic attack data
synthetic_pred = rf_model.predict(synthetic_data)
print("Classification Report for Synthetic Data:")
print(classification_report(synthetic_labels, synthetic_pred))
print("Confusion Matrix for Synthetic Data:")
print(confusion_matrix(synthetic_labels, synthetic_pred))
print("Accuracy Score for Synthetic Data:", accuracy_score(synthetic_labels, synthetic_pred))

# Visualize feature distributions
feature_names = data.columns[:-1]  # Exclude the label column

# # Plot distributions for a few features
# for feature in feature_names[:6]:  # Plot first 6 features as an example
#     plt.figure(figsize=(10, 5))
#     sns.kdeplot(data[feature], label='Real Data', shade=True)
#     sns.kdeplot(synthetic_data[:, feature_names.tolist().index(feature)], label='Synthetic Data', shade=True)
#     plt.title(f'Distribution of {feature}')
#     plt.legend()
#     plt.show()

NameError: name 'np' is not defined

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Load the synthetic data
synthetic_data_path = 'synthetic_data2.csv'
synthetic_data = pd.read_csv(synthetic_data_path)

# Drop the label column
X_synthetic = synthetic_data.drop(columns=['Label'])
y_synthetic = synthetic_data['Label']

# Split the synthetic data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_synthetic, y_synthetic, test_size=0.3, random_state=42)

In [7]:
# Initialize the Random Forest classifier data
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the synthetic data
rf_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the classifier
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

Confusion Matrix:
[[795 678]
 [832 695]]

Classification Report:
              precision    recall  f1-score   support

           0       0.49      0.54      0.51      1473
           1       0.51      0.46      0.48      1527

    accuracy                           0.50      3000
   macro avg       0.50      0.50      0.50      3000
weighted avg       0.50      0.50      0.50      3000


Accuracy Score:
0.49666666666666665


In [5]:
# Initialize the Random Forest classifier 1
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the synthetic data
rf_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the classifier
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

Confusion Matrix:
[[735 731]
 [724 810]]

Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.50      0.50      1466
           1       0.53      0.53      0.53      1534

    accuracy                           0.52      3000
   macro avg       0.51      0.51      0.51      3000
weighted avg       0.51      0.52      0.51      3000


Accuracy Score:
0.515


In [9]:
# Initialize the Random Forest classifier improved system
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the synthetic data
rf_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the classifier
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

Confusion Matrix:
[[728 776]
 [752 744]]

Classification Report:
              precision    recall  f1-score   support

           0       0.49      0.48      0.49      1504
           1       0.49      0.50      0.49      1496

    accuracy                           0.49      3000
   macro avg       0.49      0.49      0.49      3000
weighted avg       0.49      0.49      0.49      3000


Accuracy Score:
0.49066666666666664


In [11]:
# Initialize the Random Forest classifier sysn 2
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the synthetic data
rf_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the classifier
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

Confusion Matrix:
[[777 750]
 [725 748]]

Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.51      0.51      1527
           1       0.50      0.51      0.50      1473

    accuracy                           0.51      3000
   macro avg       0.51      0.51      0.51      3000
weighted avg       0.51      0.51      0.51      3000


Accuracy Score:
0.5083333333333333


In [1]:
tensorflowjs_converter --input_format=keras generator_model.h5 web_model

SyntaxError: cannot assign to operator (336770827.py, line 1)

In [ ]:
import joblib
import skl2onnx
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

# Load the scikit-learn model
model = joblib.load('random_forest_model.joblib')

# Define the initial type for the model input
initial_type = [('float_input', FloatTensorType([None, model.n_features_in_]))]

# Convert the model to ONNX format
onnx_model = convert_sklearn(model, initial_types=initial_type)

# Save the ONNX model to a file
with open('web_model/ids/model.onnx', 'wb') as f:
    f.write(onnx_model.SerializeToString())

In [10]:
generator = tf.keras.models.load_model('/Users/sanjanathyady/Desktop/project-2/backend/model/gan.h5')


In [12]:
noise = np.random.normal(0, 1, (1000, 100))
generated_data = generator.predict(noise)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [13]:
generated_data

array([[-1.        , -1.        , -1.        , -1.        , -0.53144926,
        -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        ],
       [-1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        ],
       ...,
       [-1.        , -0.9999995 , -1.        , -1.        ,  1.        ,
        -1.        ],
       [-1.        , -1.        , -1.        , -1.        ,  0.99807626,
        -1.        ],
       [-1.        , -0.9999995 , -1.        , -1.        , -1.        ,
         0.55096024]], dtype=float32)

In [9]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model

# Load the generator model
# Generate noise vector
noise = np.random.normal(0, 1, (1000, 100))

# Generate labels (assuming you have 10 classes, adjust as needed)
labels = np.random.randint(0, 10, 1000)

# Reshape labels to match the expected input shape
labels = labels.reshape(-1, 1)

# Predict with both noise and labels
generated_data = generator.predict([noise, labels])

# Print the shape of the generated data
print(generated_data.shape)

ValueError: Exception encountered when calling Functional.call().

Input 0 of layer "dense_70" is incompatible with the layer: expected axis -1 of input shape to have value 105, but received input with shape (32, 101)

Arguments received by Functional.call():
  • inputs=('tf.Tensor(shape=(32, 100), dtype=float32)', 'tf.Tensor(shape=(32, 1), dtype=int64)')
  • training=False
  • mask=('None', 'None')